name: BanWarn
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
version: 1.2.2
load: POSTWORLD
main: robske_110\BanWarn\Main
author: robske_110
website: https://github.com/robske110/BanWarn

commands:
 warn:
  description: Warns a player
  usage: "/warn <PlayerName> <Reason> [Points]"
  permission: BanWarn.command.warn
 warninfo:
  description: Outputs info about the warnings a player has
  usage: "/warninfo <PlayerName>"
  permission: BanWarn.command.warninfo
  aliases: [wi, warni, winfo]
 warnpardon:
  description: Wipes all warns of a player or removes single warns
  usage: "/warnpardon <PlayerName>"
  permission: BanWarn.command.warnpardon
  aliases: [warnp, wpardon]

permissions:
 BanWarn.command.warn:
  description: "Allows to run the /warn command"
  default: op
 BanWarn.command.warninfo:
  description: "Allows to run the /warninfo command"
  default: op
 BanWarn.command.warnpardon:
  description: "Allows to run the /warninfo command"
  default: op
